### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by pedroolvj** [pedroolvj/hearthstone_decks#1]
**### Setup**

- [ ] create project
- [ ] install axios
- [ ] install tailwind

**### Services**

- [ ] config endpoint
- [ ] create service
- [ ] create GET method

**### App** 

- [ ] create component
- [ ] create card template
- [ ] create search input
- [ ] function list decks
- [ ] function create deck
- [ ] function list cards by the deck class
- [ ] function add card to the deck (limit 2)
- [ ] function remove card from the deck
- [ ] function edit deck name & class
- [ ] function remove deck
